### ISSUE TITLE
ex:2

### ISSUE THREAD

**Issue by figaw** [praqma-training/docker-exercises#12]
In 1.1 
_"2. The Docker daemon downloads the image (alpine in this case) from Docker Hub"_ 

It doesn't fetch the image if you've already downloaded it in "part 0" of the exercise.

@sofusalbertsen

**Comment by sofusalbertsen** [comment]
Ok, so is it just a matter of adjusting the output?

**Comment by sofusalbertsen** [comment]
closed, we have reworded the section
