### ISSUE TITLE
4.5 Implementing the Gilded Rose - a wrong link

### ISSUE THREAD

**Issue by anetacamo** [praqma-training/docker-exercises#17]
in the first line the path is not src/test/java/net/praqma/codeacademy/gildedrose/TexttestFixture.java

there is no gildedrose folder on the way

it is:  src/test/java/net/praqma/codeacademy/TexttestFixture.java

**Comment by sofusalbertsen** [comment]
@anetacamo what file are we talking about here?

**Comment by anetacamo** [comment]
Hey @sofusalbertsen 

It is in the Gilded Rose - 4.5 
It was during the Code Academy in Aarhus and we were asked if there is anything not working to make an issue - But I was pretty new so I did not hit the right issue folder, haha. Sorry

**Comment by anetacamo** [comment]
https://github.com/praqma-training/gildedrose

**Comment by sofusalbertsen** [comment]
Ahh yes, fantastic :) Now I see, thanks :+1:
