### ISSUE TITLE
Make docker-compose exercises

### ISSUE THREAD

**Issue by sofusalbertsen** [praqma-training/docker-exercises#18]

**Comment by sofusalbertsen** [comment]
@Sharor and @meekrosoft 
Making this, I noticed that `--link` is depricated. [Url](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/).

Are one of you strong in the docker network section, and can give the exercise some love.

I want the exercise to progress along the lines:

* Make two containers without interconnection, exposing through host interface.
* Make connection between them, still without docker-compose.
* Make a docker-compose file persisting all the configurations in the file.

**Comment by meekrosoft** [comment]
@sofusalbertsen I can talk you through networking but don't have time to write exercises - I'm a bit behind on my side too.

**Comment by sofusalbertsen** [comment]
A-okay @meekrosoft. When do you have time?

**Comment by sofusalbertsen** [comment]
https://scalaapprentice.wordpress.com/2017/02/06/docker-running-wordpress-mysql/

**Comment by sofusalbertsen** [comment]
https://docs.docker.com/engine/userguide/networking/configure-dns/

**Comment by sofusalbertsen** [comment]
https://docs.docker.com/compose/wordpress/
