### ISSUE TITLE
Docker on windows natively lab

### ISSUE THREAD

**Issue by sofusalbertsen** [praqma-training/docker-exercises#39]
* Use your knowledge from yesterday to setup a windows container
* Deploy a hello world web app

**Comment by Sharor** [comment]
So having spent a day on this : 

Its not that simple. All examples use visual studio to publish .NET asp framework apps, and requires you to build from Visual Studio. 

The few commandline examples I did make work, are incredibly involved and too heavy on the .NET side to be of use for this. 

I suggest we use some pre-provisioned images, and show some dockerfiles and then move on. 

@sofusalbertsen @meekrosoft  thoughts ?

**Comment by Sharor** [comment]
This : https://github.com/Microsoft/dotnet-framework-docker-samples

was the most reasonable guide for the other approach, but its quite microsoft  heavy (Visual Studio stuff)

**Comment by meekrosoft** [comment]
@Sharor Yes, I agree - let's keep it simple.  Pre-baked images are sufficient.  But it would be useful to look at windows dockerfiles.  Is there a simple way to do this?

**Comment by Sharor** [comment]
@meekrosoft Yep and Im on it.

I think this should do the trick
