### ISSUE TITLE
Kubernetes as a docker orchestration platform

### ISSUE THREAD

**Issue by sofusalbertsen** [praqma-training/docker-exercises#46]
Kubernetes as a docker orchestration platform
Introduction (presentation)
Minikube
Kubectl 
Deployment
Service
KubeAdm multi node cluster
Secrets
Ingress (Nginx vs Traefik)
Health checks

**Comment by KamranAzeem** [comment]
Wouldn't it be too much for attendees coming in to learn docker, to learn "a lot" about Kubernetes?

**Comment by Sharor** [comment]
@KamranAzeem you think it's too much ? 

What would you cut ?  
@meekrosoft  you also think it might be too much, and we should stick with Docker Windows and prepare Kube in case we need it?

**Comment by KamranAzeem** [comment]
Yes. That is how I see it. From a student's perspective, it is too much. Perhaps Docker and Kubernetes could be two separate sessions on two separate days. Kubernetes is not a single machine or a single service. It involves a lot of concepts and there are a lot of moving parts. Students will be confused trying to figure out two technologies and may end up learning neither of them. For Docker orchestration, may be the following order and technologies could be used: Docker -> Docker-Compose -> Docker Swarm . When these three Docker related technologies are covered, (a good idea), then it would be a good idea to present Kubernetes as the orchestration solution highlighting weaknesses in Docker Swarm, and highlighting strengths in Kubernetes. But this can't be done in a single day. IMHO.

**Comment by meekrosoft** [comment]
I agree with Kamran in sentiment, but we have announced that the course includes kubernetes so we should try to cover that in as simple a way as possible.  I could see that we should make a 1 day course on running applications in k8s but for now we can just show how to deploy, expose, and upgrade services on a kluster.  Preferably with pre-made yaml.

**Comment by Sharor** [comment]
I have the material for this, so that's great. Then we can see how people receive it, and just take it from there. 😉 thanks @KamranAzeem and @meekrosoft

**Comment by sofusalbertsen** [comment]
Closing this one. Further discussion can be made in the new repo: https://github.com/praqma-training/kubernetes-katas
