### ISSUE TITLE
Kubernetes material should be separated from Docker

### ISSUE THREAD

**Issue by KamranAzeem** [praqma-training/docker-exercises#52]
Kubernetes material should ideally be in a separate repo "kubernetes excercises", so the students are not confused when they are trying to focus on learning one technology at a time.
Mixing Kubernetes in a Docker course will be overwhelming for the students, and I would not want to do it, if it is a course I am teaching. :)

**Comment by sofusalbertsen** [comment]
Has been resolved with : https://github.com/praqma-training/kubernetes-katas

**Comment by sofusalbertsen** [comment]
https://github.com/praqma-training/kubernetes-katas/issues/1
