### ISSUE TITLE
Text in exercise 4 refers to unknown stuff

### ISSUE THREAD

**Issue by chopse** [praqma-training/docker-exercises#55]
In exercise 4 (attaching and executing), the text refers to the nginx container that have not been in use or explained before (it is in exercise 5 though). Also since exercise 3 is about removing and pruning, it's a big risk that the user have no containers running to attach to.
Some sort of setup or change of order in the exercises is needed.

**Comment by sofusalbertsen** [comment]
Thanks for the feedback!
Commit https://github.com/praqma-training/docker-exercises/commit/3b15d6ec3783e3c8e2079d15fa55ede5f2634adb have fixed this.
