### ISSUE TITLE
"8-sharing-containers" should be renamed to "8-storing and retrieving container images "

### ISSUE THREAD

**Issue by KamranAzeem** [praqma-training/docker-exercises#58]
The word "sharing" brings a picture of people exchanging software on floppies/usbs, whereas the material of the chapter talks about storing the container **image** on dockerhub/registry . There needs to be some more material on retrieving the image you just stored, to give it a complete look.

**Comment by sofusalbertsen** [comment]
Thanks for your input Kamran.
Could storing and retrieving also point to the docker container load/save command?
Regardless will give it some more information

**Comment by sofusalbertsen** [comment]
Made a action task for this.
