### ISSUE TITLE
check terraform scripts for windows VM provisioning accept input vars

### ISSUE THREAD

**Issue by sami-alajrami** [praqma-training/docker-exercises#60]
we need to check if `terraform apply -var xyz=zxy ..` works with terraform on @sofusalbertsen and maybe @Sharor machines.

It possibly need single quotes .. `terraform apply -var 'xyz=zxy' ..`

The scripts in question are : https://github.com/Praqma/provision-win-docker

**Comment by Sharor** [comment]
We made it spin up now, @sami-alajrami  - I just need to go verify they work as they should. Sofus solved this :)

**Comment by sofusalbertsen** [comment]
We need to check the commands provided. I changed in the configfile!=best solution.

**Comment by sami-alajrami** [comment]
If the single quotes don't work, I have tried the following docker image and it works  : 

``` 
$ cd terraform 
$ docker run -i -t -v $(pwd):/tmp  hashicorp/terraform:light init /tmp; terraform plan  -var admin_password=MyWindowsServer2016ValidPassword! -var instance_count=1 
```
Note that the command above is `plan` which plans but does not create resources.

**Comment by sofusalbertsen** [comment]
@sami-alajrami  the VM's are painfully slow at extracting files. I think it's the harddisk type used. Can you change so that it's their high performance SSD drives that are used? 
Link: https://aws.amazon.com/ebs/details/

**Comment by sami-alajrami** [comment]
@sofusalbertsen the VMs take by default [the general purpose ssd](https://aws.amazon.com/about-aws/whats-new/2014/06/16/introducing-the-amazon-ebs-general-purpose-ssd-volume-type/) ebs volumes. 

> Backed by Solid-State Drives (SSDs), General Purpose (SSD) volumes provide the ability to burst to 3,000 IOPS per volume, independent of volume size, to meet the performance needs of most applications and also deliver a consistent baseline of 3 IOPS/GB. 

 the next level is the provisioned IOPS ssd. Here is a [comparison](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html).

--- 
Would like to change the volumes to be provisioned IOPS?

**Comment by sofusalbertsen** [comment]
@sami-alajrami  we just had a problem with the machines beeing really slow at downloading+unpacking images for the training. 
But a better thing to do is making a script that pulls down the following images on the machines:
microsoft/nanoserver
microsoft/windowsservercore
microsoft/mssql-server-windows-developer
microsoft/dotnet-framework-samples
microsoft/dotnet-framework-build
microsoft/iis

Is that doable in the terraform script?

**Comment by sami-alajrami** [comment]
@sofusalbertsen yes this is doable. Pulling windows images is naturally slow due to their large size and I imagine it gets slower when several people pull them at the same time.

I would suggest to do it in the Packer AMI VM image instead because doing it in terraform means that each VM would be pulling the images separately and the provisioning time of VMs would take much longer. With Packer, only the VM image will pull the docker images.

**Comment by sofusalbertsen** [comment]
And just checked the script for accpetance of variables, and it works with:
`./terraform apply -var instance_count=10 -var admin_password=Praqm@2017`
I think the reason why it did _not_ work last time was because i did:
`./terraform plan -var instance_count=10 -var admin_password=Praqm@2017`
and 
`./terraform apply` without any variables.
But now everything works according to documentation :)

**Comment by sofusalbertsen** [comment]
@sami-alajrami could be an idea to do it in packer.
Only thing there is if we plan to reuse the image after some time, then the original pulls will be outdated.
But I do not know if the strategy is to make a new AMI for every time we run this training.
If it is best practice, then yes by all means do it once instead of on each VM :)

**Comment by sami-alajrami** [comment]
@sofusalbertsen good point, it is not necessarily a strategy. But I guess that could work. 

It is about what is more practical for you. If you are OK with waiting for VMs provisioning using terraform to pull each image, then we can do it in terraform and have VMs up to date. If you don't  have the patience, then we can do it in packer :)

It is your call. :-D

**Comment by sofusalbertsen** [comment]
When spinning up servers before a training i have all the time in the world, as long as i know it will take time ;)

**Comment by sami-alajrami** [comment]
@sofusalbertsen it is done in terraform now. You can test it whenever you have the time and ping me if anything else is needed.

**Comment by sofusalbertsen** [comment]
@sami-alajrami thanks a lot, you have really been helpful, much appreciated!

**Comment by sofusalbertsen** [comment]
@sami-alajrami  this works now, sorry for keeping you waiting so long!
