### ISSUE TITLE
Error in kubernetes exercise 1

### ISSUE THREAD

**Issue by veloek** [praqma-training/docker-exercises#73]
In step 1.3 there is a command to export the config to yaml:

`kubectl get deployment ngingo -o yaml -n <namespace> myapp-deployment.yml`

It's missing a `>` and should be:

`kubectl get deployment ngingo -o yaml -n <namespace> > myapp-deployment.yml`

**Comment by sofusalbertsen** [comment]
Thanks for the issue @veloek, seems like to fixed it in your commit: 8b4155be7c9f62e015d235034512e0a7e19ad3dc
